#+OPTIONS: title:t date:t author:t email:t
#+OPTIONS: toc:t h:6 num:nil |:t todo:nil
#+OPTIONS: *:t -:t ::t <:t \n:t e:t creator:nil
#+OPTIONS: f:t inline:t tasks:t tex:t timestamp:t
#+OPTIONS: html-preamble:t html-postamble:nil

#+TITLE:   Key R resources that will change your R life...
#+DATE:	  {{{time(%B %d\, %Y)}}}
#+AUTHOR:  Marie-Hélène Burle
#+CREATOR: Simon Fraser University, Research Commons
#+EMAIL:   msb2@sfu.ca

... and that you *really* should use.

* Learning R

These days, there is a shortage of courses on R. And the few courses offered don't always make use of the more novel and more efficient tools. The good news however is that the internet is a gold mine of free, open-source, amazing resources. If you know where to look, you can learn R in a really productive way. The Research Commons also offers a growing number of R resources.

** On-line resources

Several excellent books on R are-on top of their paper version-available as [[https://bookdown.org/][bookdowns]]. There are also great manuals and tutorials.

*** Getting started with R and the tidyverse

The book [[http://r4ds.had.co.nz/index.html][R for Data Science by Garrett Grolemund and Hadley Wickham]] is a must read for all beginner/intermediate R users, as well as advanced users not familiar with the tidyverse. This book will get you started with good habits and is an excellent introduction to R.

*** Writing readable and well-formatted code

http://adv-r.had.co.nz/Style.html

https://google.github.io/styleguide/Rguide.xml

[[http://style.tidyverse.org/][the tidyverse style guide]]

*** Understanding R as a programming language

The book [[https://adv-r.hadley.nz/][Advanced R by Hadley Wickham]] will give you a better understanding of R as a programming language and help you get to the next level of R writing.

[[http://adv-r.had.co.nz/][The first edition]] of that book was more focuses on base R and less on the tidyverse and is also worth a read.

*** Writing your own packages

The book [[http://r-pkgs.had.co.nz/][R packages by Hadley Wickham]] will get you started if you want to write your own packages.

The on-line manual [[https://cran.r-project.org/doc/manuals/R-exts.html][Writing R Extensions by the R Core Team]] gives a more dense and exhaustive documentation if you need something that is not in Hadley's book.

*** GIS in R

The tutorials [[https://data.cdrc.ac.uk/tutorial/an-introduction-to-spatial-data-analysis-and-visualisation-in-r][An Introduction to Spatial Data Analysis and Visualisation in R by Guy Lansley and James Cheshire]] as well as the book [[https://geocompr.robinlovelace.net/][Geocomputation with R by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow]] will teach you how to map data and conduct spacial data analysis in R or how to bridge R and [[https://www.qgis.org/en/site/][QGIS]].

** Resources at SFU

- rc service
- workshops
- books

[[https://software-carpentry.org/][Software Carpentry]] and [[http://www.datacarpentry.org/][Data Carpentry]], now merged under [[http://carpentries.org/][the Carpentries]]

[[http://sciprog.ca/][SciProg]] is 

For students in the department of biology, 

[[][Research Commons R peers].

* Getting help

Where can you find help if you cannot figure out how to do something
link to other section

- rc
- sites


* Getting involved in the R community

[[https://ropensci.org/blog/][rOpenSci]]

[[https://rladies.org/][R Ladies]], an organization promoting gender diversity in the R community, recently opened [[https://www.meetup.com/R-Ladies-Vancouver/][a new chapter in Vancouver]].

*** Answering questions

Obviously, 

*** Contributing code

**** Filling issues and submitting pull request

[[https://github.com/][GitHub]]

**** Submitting packages



* Keeping up to date with R

Listing only free resources. Some paid options too.


** Blogs

Rblogger



