#+OPTIONS: title:t date:t author:t email:t
#+OPTIONS: toc:t h:6 num:nil |:t todo:nil
#+OPTIONS: *:t -:t ::t <:t \n:t e:t creator:nil
#+OPTIONS: f:t inline:t tasks:t tex:t timestamp:t
#+OPTIONS: html-preamble:t html-postamble:nil

#+TITLE:   Before we start
#+DATE:	  {{{time(%B %d\, %Y)}}}
#+AUTHOR:  Marie-Hélène Burle
#+SUBTITLE: Simon Fraser University, Research Commons
#+EMAIL:   msb2@sfu.ca

* To do before the workshop

- phone on silent
- stop slack
- stop skype

* Information to give at the start of the workshop

** Start in a fun tone

** Check that they can see (font size ok?) and hear me ok

** Introduce myself and the helpers

- write my name and contact on the board

** Explain code to get help from helpers and code to stop me


** Reassure that everything covered is in a website that is fully available

So they don't have to take notes frantically

** Warning about different tools

In workshops for beginners, it is good to use the tools that the workshop attendees are using to reduce confusion. But this is not a beginner workshop and I will use the tools that I usually use, some of which being different than what you are familiar with, because I think that exposure to tips and tricks that you don't know can give you new ideas of what you could do and open new horizons. If you are confused however, do not hesitate to stop me.

This might seem non-pedagogical, but I have personally be inspired greatly by cool tricks that I gleaned during workshops and which were not the subject of the workshop. If you see something new, you might then look it up by yourself and find amazing new tricks.

So I will not use RStudio, that I imagine many of you are using, but emacs ESS. And I will use snippets so that you can see how wonderful they are (and they do exist in RStudio. And if you aren't using snippets, you really should).

** Make sure they all have latest R, RStudio if need be, and tidyverse

** Make sure they have internet access and give the website of the workshop

- write it on the board



