#+OPTIONS: title:t date:t author:t email:nil
#+OPTIONS: toc:t h:6 num:nil |:t todo:nil
#+OPTIONS: *:t -:t ::t <:t \n:t e:t creator:nil
#+OPTIONS: f:t inline:t tasks:t tex:t timestamp:t
#+OPTIONS: html-preamble:t html-postamble:nil

#+TITLE:   Help guide for R users
#+DATE:	   {{{time(%B %d\, %Y)}}}
#+AUTHOR:  Marie-Hélène Burle
#+EMAIL:   msb2@sfu.ca

R is a fast evolving and increasingly popular language. It started as a statistical analysis and graphing language written by data scientists, but its capabilities expended widely beyond this. Amongst the many benefits of R are the countless packages being incessantly developed and the fact that R is fully open source. But another appeal to R is its large and incredibly active on-line community and the amazing resources that it produces. Surprisingly however, a lot of graduate students don't make much use of these freely available and extremely high quality resources. This document intends to list some of them, as well as more traditional resources, in hope that graduate students will start writing better code with much less pain and much more joy.

* List of resources

** Within R itself

src_R[:eval no]{vignette()}
src_R[:eval no]{help.start()}
src_R[:eval no]{?}

** On-line resources

Listing only free resources. Some paid options too.

*** On-line R books in bookdown

[[https://bookdown.org/][A list of R books written in R Markdown thanks to the package bookdown]].

*** Blogs

Rblogger

*** On-line community

- so
- rsc
- twitter
- slack r4ds
- mailing lists

** Locally

*** At SFU

- rc service
- workshops
- books

*** In town

R Ladies new chapter






* Where to go when and how

** Learning R

*** Beginners

An amazing starting place to learn R is the book by Garrett Grolemund and Hadley Wickham "R for Data Science". This is also a great resource for R users who aren't familiar with the tidyverse. It is freely available [[http://r4ds.had.co.nz/index.html][on-line]], but also exists in a book format.

[[https://software-carpentry.org/][Software Carpentry]] and [[http://www.datacarpentry.org/][Data Carpentry]], now merged under [[http://carpentries.org/][the Carpentries]]

[[http://sciprog.ca/][SciProg]] is 

For students in the department of biology, 

[[link: where is the link??? I can't find it... Maybe R support should be better advertised :) ][Research Commons R peers].

*** Intermediates

For intermediate users willing to understand the language better, or for people new to R but already familiar with other languages, a great resource is another book by Hadley Wickham, "Advanced R". It is also freely accessible [[http://adv-r.had.co.nz/][on-line]].

*** Advanced users

Hadley also wrote a book on how to write your own packages. This one too, is available [[http://r-pkgs.had.co.nz/][on-line]].

*** GIS in R

R can also be used to map data and conduct spacial data analysis. [[https://data.cdrc.ac.uk/tutorial/an-introduction-to-spatial-data-analysis-and-visualisation-in-r][This series of tutorials]] by Guy Lansley and James Cheshire and [[https://geocompr.robinlovelace.net/][the book "Geocomputation with R"]] by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow are good on-line resources to get started on this.

** Formatting code

http://adv-r.had.co.nz/Style.html

https://google.github.io/styleguide/Rguide.xml

[[http://style.tidyverse.org/][the tidyverse style guide]]

** Getting help with R

The best way to get help with R is to make a minimal reproducible example: https://www.tidyverse.org/help/#where-to-ask

 ("reprex" in R jargon).
[[https://stackoverflow.com/questions/tagged/r][Stack Overflow]]

[[https://stackoverflow.com/help/tagging][tags]]

Hadley Wickham [[http://adv-r.had.co.nz/Reproducibility.html][How to write a reproducible example]] 
Stack Overflow [[https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example][How to make a great R reproducible example?]]

https://community.rstudio.com/t/welcome-to-the-rstudio-community/8

https://community.rstudio.com/guidelines

https://support.rstudio.com/hc/en-us/articles/200552336

** Getting involved in the R community

[[https://ropensci.org/blog/][rOpenSci]]


[[https://rladies.org/][R Ladies]], an organization promoting gender diversity in the R community, recently opened [[https://www.meetup.com/R-Ladies-Vancouver/][a new chapter in Vancouver]].

*** Answering questions

Obviously, 

*** Contributing code

**** Filling issues and submitting pull request

[[https://github.com/][GitHub]]

**** Submitting packages

